### ISSUE TITLE
能把目录树做成vuepress那种文档目录树吗？

### ISSUE THREAD

**Issue by dianso** [LiuYinCarl/mssws#1]

**Comment by LiuYinCarl** [comment]
应该是可以的，通过简单修改代码，后端可以提供目录列表给前端，不过需要重写index 页面。目前这样的设计是基于两个目的：1. 支持通过浏览器的 Ctrl+f 快捷键来快速搜索文章，2. 大部分个人博客数量应该在300篇以下，目录结构不是太有必要。
