### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by candywzt** [LiuYinCarl/mssws#2]
运行结果如图所示，可以访问，但是md文件点开会直接下载，pdf文件无法打开，显示缺少PDF文件
![2](https://user-images.githubusercontent.com/44725213/130342243-a4696c6f-5aeb-4eae-93de-3a093cebe997.png)

**Comment by LiuYinCarl** [comment]
你好，麻烦提供一下如下信息：
- 使用的浏览器的类型和版本
- 部署的目录机构，在 mssws 目录下执行 `tree` 或者 `find .` 命令

另外，我猜测 pdf 文件找不到的问题是因为你的文件名中含有空格，可以先试一下去除空格。

**Comment by LiuYinCarl** [comment]
从你的截图中可以看到，程序提供的文件名检测工具检测到了你的文件名中含有空格（`space in filename`），但是程序默认不会阻止你启动服务。

**Comment by LiuYinCarl** [comment]
关于你说的点击 markdown 文件会直接下载的问题，可以尝试先访问示例网站（http://man6.org/）上的 markdown 文件来，看看会不会也直接下载，这样子可以知道是不是使用的浏览器导致的问题。

**Comment by LiuYinCarl** [comment]
关于你说的点击 markdown 文件会直接下载的问题，可以尝试先访问[示例网站](http://man6.org)上的 markdown 文件来，看看会不会也直接下载，这样子可以知道是不是使用的浏览器导致的问题。

**Comment by LiuYinCarl** [comment]
@candywzt 请问现在还有问题吗，如果没有的话我将关闭这个 issue.
