### ISSUE TITLE
配置网站标题不生效

### ISSUE THREAD

**Issue by bill5522** [LiuYinCarl/mssws#3]
配置config.json文件，修改SiteTitle项，网站标题不生效。要修改main.go文件的SiteTitle才生效。
默认网站标题是index.html

**Comment by LiuYinCarl** [comment]
_刚才失误关掉了该 issue._ 

感谢反馈，这个 Bug 已经修复了，你可以尝试拉取最新版本再测试一下。

**Comment by bill5522** [comment]
感谢！感谢！感谢！
